apiVersion: v1
kind: Service
metadata:
  name: job-frontend
  namespace: talentocolombia
spec:
  type: NodePort
  selector:
    app: job-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008